#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
*/

require __DIR__.'/vendor/autoload.php';

$status = (require __DIR__.'/bootstrap/app.php')
    ->handleCommand(new \Symfony\Component\Console\Input\ArgvInput);

exit($status);
